Submitted by: Noor Malhotra,

Roll No.: 2520999321,

Subject: Introduction To Data Science and AI,

Course: BBA (DSAI),

Chitkara University

In [120]:

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (Colab: upload movie.csv first)
df = pd.read_csv('movie.csv')

# Quick preview
df.head()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

In [121]:
print("Columns:", list(df.columns))
print("\nShape:", df.shape)
print("\nNulls per column:\n", df.isnull().sum())

# Standardize column names (lowercase, strip spaces)
df.columns = [c.strip() for c in df.columns]

# If your columns use different names, map them to the expected names:
# (uncomment and change the right side if needed)
col_map = {
    # 'title':'movie_title',
    # 'actor1':'actor_1_name',
    # 'Actor 1':'actor_1_name'
}
# df.rename(columns=col_map, inplace=True)

# Show first rows after rename
df.head()

Columns: ['title', 'year', 'color', 'content_rating', 'duration', 'director_name', 'director_fb', 'actor1', 'actor1_fb', 'actor2', 'actor2_fb', 'actor3', 'actor3_fb', 'gross', 'genres', 'num_reviews', 'num_voted_users', 'plot_keywords', 'language', 'country', 'budget', 'imdb_score']

Shape: (4916, 22)

Nulls per column:
 title                0
year               106
color               19
content_rating     300
duration            15
director_name      102
director_fb        102
actor1               7
actor1_fb            7
actor2              13
actor2_fb           13
actor3              23
actor3_fb           23
gross              862
genres               0
num_reviews         49
num_voted_users      0
plot_keywords      152
language            14
country              5
budget             484
imdb_score           0
dtype: int64

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

In [122]:
for col in ['gross','budget','num_voted_users','imdb_score','duration','year']:
    if col in df.columns:
        # remove commas, currency symbols and cast
        df[col] = (df[col]
                   .astype(str)
                   .str.replace('[\$,]', '', regex=True)   # remove $ and commas
                   .replace({'nan':'', '': pd.NA})
                  )
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Confirm dtypes
df[['gross','budget','num_voted_users','imdb_score','duration','year']].dtypes

<>:6: SyntaxWarning: invalid escape sequence '\$'
<>:6: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-1181133853.py:6: SyntaxWarning: invalid escape sequence '\$'
  .str.replace('[\$,]', '', regex=True)   # remove $ and commas

gross              float64
budget             float64
num_voted_users      int64
imdb_score         float64
duration           float64
year               float64
dtype: object

In [123]:
if 'genres' in df.columns:
    # common separators: '|' or ',' — try both
    df['genres'] = df['genres'].astype(str).str.replace(',', '|')  # unify separators
    df['genres'] = df['genres'].str.split('|')
    df_exploded = df.explode('genres')
else:
    df_exploded = df.copy()

In [124]:
# Q1
if 'movie_title' in df.columns:
    df.sort_values(by='gross', ascending=False)[['movie_title','gross']].head(5)
else:
    df.sort_values(by='gross', ascending=False).head(5)

In [125]:
# Q2
df[df['year'] > 2010]['imdb_score'].mean()

np.float64(6.244799344799344)

In [126]:
# Q3
df[df['director_name'] == 'Christopher Nolan'].shape[0]

8

In [127]:
# Q4 (uses exploded df_exploded)
df_exploded['genres'].value_counts().head(1)

genres
Drama    2533
Name: count, dtype: int64

In [128]:
# Q5
df[df['country'] == 'USA']['budget'].mean()

np.float64(35206575.84275256)

In [129]:
# Check all column names
print(list(df.columns))

['title', 'year', 'color', 'content_rating', 'duration', 'director_name', 'director_fb', 'actor1', 'actor1_fb', 'actor2', 'actor2_fb', 'actor3', 'actor3_fb', 'gross', 'genres', 'num_reviews', 'num_voted_users', 'plot_keywords', 'language', 'country', 'budget', 'imdb_score']

In [130]:
# Q6
# Q6 - corrected
df['actor1'].value_counts().head(1)

actor1
Robert De Niro    48
Name: count, dtype: int64

In [131]:
# Q7
df[df['content_rating'] == 'PG-13']['duration'].mean()

np.float64(111.04893617021277)

In [132]:
# Q8
df[df['gross'] > 100_000_000].shape[0]

578

In [133]:
# Q9
df.groupby('director_name')['gross'].sum().sort_values(ascending=False).head(5)

director_name
Steven Spielberg     4.114233e+09
Michael Bay          2.195444e+09
Peter Jackson        2.112884e+09
James Cameron        1.948126e+09
Christopher Nolan    1.813228e+09
Name: gross, dtype: float64

In [134]:
# Q10
df[df['language'] == 'English']['num_voted_users'].mean()

np.float64(85991.9153208206)

In [135]:
# Q11
df['year'].value_counts().head(1)

year
2009.0    253
Name: count, dtype: int64

In [136]:
# Q12
if 'color' in df.columns:
    df['color'].value_counts(normalize=True) * 100
else:
    print("No 'color' column found in dataset.")

In [137]:
#Answer Q1: The top 5 highest grossing movies are shown above. The highest grossing title is *MovieTitle* with $X gross.